_this removeItem 'l6AA_DRUGS2';
for "_i" from 1 to 3 do {_this addItemToBackpack 'kat_TXA'};
for "_i" from 1 to 3 do {_this addItemToBackpack 'ACE_morphine'};
for "_i" from 1 to 2 do {_this addItemToBackpack 'ACE_epinephrine'};
for "_i" from 1 to 2 do {_this addItemToBackpack 'kat_naloxone'};
for "_i" from 1 to 2 do {_this addItemToBackpack 'kat_EACA'};
for "_i" from 1 to 2 do {_this addItemToBackpack 'kat_phenylephrine'};
for "_i" from 1 to 2 do {_this addItemToBackpack 'kat_lidocaine'};
for "_i" from 1 to 2 do {_this addItemToBackpack 'ACE_adenosine'};
for "_i" from 1 to 3 do {_this addItemToBackpack 'kat_fentanyl'};
_this addItemToBackpack 'kat_CarbonateItem';
_this addItemToBackpack 'kat_PenthroxItem';
